/* Generated by Together */

package org.nii.niis.niim.service;

import java.util.List;

/**
 * 사용자 정보 관리 Service
 * 
 * 로그인, 회원가입, 개인정보 입력 기능을 제공
 */
public interface LoginService {

	/**
	 * 사용자 로그인
	 * @param id
	 * @param pw
	 * @return List
	 * @throws Exception
	 */
	List<UserVO> getLoginCheck(String id, String pw) throws Exception;

	/**
	 * gpki 사용자 로그인
	 * @param id
	 * @param pw
	 * @return List
	 * @throws Exception
	 */
	List<UserVO> getLoginCheckGpki(String pw) throws Exception;
    /**
     * 회원가입 
     */
    boolean setUserInfo(UserVO userVO) throws Exception;

    /**
     * 개인정보의 입력 / 수정을 처리하는 메소드 
     */
    boolean setPersonData() throws Exception;

    /**
     * 개인정보 불러오기 
     */
    UserVO getPersonData() throws Exception;

    
    /**
	 * 사용자 로그 기록
	 * @param sendMap
	 * @throws Exception
	 */
	void insertLoginLog(String usrMgno, String st, String acsIp, String reqMgno, String systemCde) throws Exception;
}


