/* Generated by Together */

package org.nii.niis.niim.service;

import java.io.Serializable;

import org.apache.commons.lang.builder.ToStringBuilder;

/**
 * 사용자 정보
 * @stereotype entity 
 */
@SuppressWarnings("serial")
public class UserVO implements Serializable {	
	/** 아이디 */
	private String id;
	/** 이름 */
	private String name;
	/** 주민등록번호 */
	private String ihidNum;
	/** 이메일주소 */
	private String email;
	/** 비밀번호 */
	private String password;
	/** 비밀번호 힌트 */
	private String passwordHint;
	/** 비밀번호 정답 */
	private String passwordCnsr;
	/** 사용자구분 */
	private String userSe;
	/** 조직(부서)ID */
	private String orgnztId;
	/** 조직(부서)명 */
	private String orgnztNm;
	/** 고유아이디 */
	private String uniqId;
	/** 로그인 후 이동할 페이지 */
	private String url;
	/** 사용자 IP정보 */
	private String ip;
	/** GPKI인증 DN */
	private String dn;
	/** 직위코드 */
	private String posCd;
	/** 성과자료인가여부 */
	private String pdtdataAuthYn;
	/** 비취인가여부 */
	private String shAuthYn;
	/** 수정 여부 */
	private String mdAuthYn;
	
	/** 시스템인가여부 */
	private String sysAuthYn;
	/** 상태 */
	private String st;
	
	/** 최종개인정보수정완료이후 개월수 */
	private double lastModMonth;	
	
	/** 공공측량 관리 임시권한 */
	private String psAuthCd;
	
	/** 사용자 전화번호*/
	private String usrTel;
	
	/** 사용자 사용권한*/
	private String useAt;
	
	/** 사용자 성과종류권한*/
	private String pkindAt;
	
	/** 사용자 관리권한*/
	private String applyAt;
	
	/** 소속 팀 */
	private String teamCd;
	/** 사용 권한*/
	private String useCd;
	
	/** 소속 */
	private String post;
	/** 사용자 생년월일 */
	private String usrRnum1;
	/** 부서 */
	private String department;
	/** 직급 */
	private String position;
	/** 직급 */
	private String cause;
	/** 직급 */
	private String helpYn;
	
	
	/**
	 * id attribute 를 리턴한다.
	 * @return String
	 */
	public String getId() {
		return id;
	}
	/**
	 * id attribute 값을 설정한다.
	 * @param id String
	 */
	public void setId(String id) {
		this.id = id;
	}
	/**
	 * name attribute 를 리턴한다.
	 * @return String
	 */
	public String getName() {
		return name;
	}
	/**
	 * name attribute 값을 설정한다.
	 * @param name String
	 */
	public void setName(String name) {
		this.name = name;
	}
	/**
	 * ihidNum attribute 를 리턴한다.
	 * @return String
	 */
	public String getIhidNum() {
		return ihidNum;
	}
	/**
	 * ihidNum attribute 값을 설정한다.
	 * @param ihidNum String
	 */
	public void setIhidNum(String ihidNum) {
		this.ihidNum = ihidNum;
	}
	/**
	 * email attribute 를 리턴한다.
	 * @return String
	 */
	public String getEmail() {
		return email;
	}
	/**
	 * email attribute 값을 설정한다.
	 * @param email String
	 */
	public void setEmail(String email) {
		this.email = email;
	}
	/**
	 * password attribute 를 리턴한다.
	 * @return String
	 */
	public String getPassword() {
		return password;
	}
	/**
	 * password attribute 값을 설정한다.
	 * @param password String
	 */
	public void setPassword(String password) {
		this.password = password;
	}
	/**
	 * passwordHint attribute 를 리턴한다.
	 * @return String
	 */
	public String getPasswordHint() {
		return passwordHint;
	}
	/**
	 * passwordHint attribute 값을 설정한다.
	 * @param passwordHint String
	 */
	public void setPasswordHint(String passwordHint) {
		this.passwordHint = passwordHint;
	}
	/**
	 * passwordCnsr attribute 를 리턴한다.
	 * @return String
	 */
	public String getPasswordCnsr() {
		return passwordCnsr;
	}
	/**
	 * passwordCnsr attribute 값을 설정한다.
	 * @param passwordCnsr String
	 */
	public void setPasswordCnsr(String passwordCnsr) {
		this.passwordCnsr = passwordCnsr;
	}
	/**
	 * userSe attribute 를 리턴한다.
	 * @return String
	 */
	public String getUserSe() {
		return userSe;
	}
	/**
	 * userSe attribute 값을 설정한다.
	 * @param userSe String
	 */
	public void setUserSe(String userSe) {
		this.userSe = userSe;
	}
	/**
	 * orgnztId attribute 를 리턴한다.
	 * @return String
	 */
	public String getOrgnztId() {
		return orgnztId;
	}
	/**
	 * orgnztId attribute 값을 설정한다.
	 * @param orgnztId String
	 */
	public void setOrgnztId(String orgnztId) {
		this.orgnztId = orgnztId;
	}
	/**
	 * uniqId attribute 를 리턴한다.
	 * @return String
	 */
	public String getUniqId() {
		return uniqId;
	}
	/**
	 * uniqId attribute 값을 설정한다.
	 * @param uniqId String
	 */
	public void setUniqId(String uniqId) {
		this.uniqId = uniqId;
	}
	/**
	 * url attribute 를 리턴한다.
	 * @return String
	 */
	public String getUrl() {
		return url;
	}
	/**
	 * url attribute 값을 설정한다.
	 * @param url String
	 */
	public void setUrl(String url) {
		this.url = url;
	}
	/**
	 * ip attribute 를 리턴한다.
	 * @return String
	 */
	public String getIp() {
		return ip;
	}
	/**
	 * ip attribute 값을 설정한다.
	 * @param ip String
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}
	/**
	 * dn attribute 를 리턴한다.
	 * @return String
	 */
	public String getDn() {
		return dn;
	}
	/**
	 * dn attribute 값을 설정한다.
	 * @param dn String
	 */
	public void setDn(String dn) {
		this.dn = dn;
	}
	/**
	 * @return the orgnztNm
	 */
	public String getOrgnztNm() {
		return orgnztNm;
	}
	/**
	 * @param orgnztNm the orgnztNm to set
	 */
	public void setOrgnztNm(String orgnztNm) {
		this.orgnztNm = orgnztNm;
	}
	

	public String getPosCd() {
		return posCd;
	}
	public void setPosCd(String posCd) {
		this.posCd = posCd;
	}
	
		
	public String getSt() {
		return st;
	}
	public void setSt(String st) {
		this.st = st;
	}
	
	public double getLastModMonth() {
		return lastModMonth;
	}
	public void setLastModMonth(double lastModMonth) {
		this.lastModMonth = lastModMonth;
	}
	public String toString() {
    	return ToStringBuilder.reflectionToString(this);
    }
	
	public String getUsrTel() {
		return usrTel;
	}
	public void setUsrTel(String usrTel) {
		this.usrTel = usrTel;
	}
	public String getTeamCd() {
		return teamCd;
	}
	public void setTeamCd(String teamCd) {
		this.teamCd = teamCd;
	}
	public String getUseCd() {
		return useCd;
	}
	public void setUseCd(String useCd) {
		this.useCd = useCd;
	}
	public String getPsAuthCd() {
		return psAuthCd;
	}
	public void setPsAuthCd(String psAuthCd) {
		this.psAuthCd = psAuthCd;
	}
	public String getPdtdataAuthYn() {
		return pdtdataAuthYn;
	}
	public void setPdtdataAuthYn(String pdtdataAuthYn) {
		this.pdtdataAuthYn = pdtdataAuthYn;
	}
	public String getShAuthYn() {
		return shAuthYn;
	}
	public void setShAuthYn(String shAuthYn) {
		this.shAuthYn = shAuthYn;
	}
	public String getMdAuthYn() {
		return mdAuthYn;
	}
	public void setMdAuthYn(String mdAuthYn) {
		this.mdAuthYn = mdAuthYn;
	}
	public String getSysAuthYn() {
		return sysAuthYn;
	}
	public void setSysAuthYn(String sysAuthYn) {
		this.sysAuthYn = sysAuthYn;
	}
	public String getUseAt() {
		return useAt;
	}
	public void setUseAt(String useAt) {
		this.useAt = useAt;
	}
	public String getPkindAt() {
		return pkindAt;
	}
	public void setPkindAt(String pkindAt) {
		this.pkindAt = pkindAt;
	}
	public String getApplyAt() {
		return applyAt;
	}
	public void setApplyAt(String applyAt) {
		this.applyAt = applyAt;
	}
	
	public String getPost() {
		return post;
	}
	public void setPost(String post) {
		this.post = post;
	}
	public String getUsrRnum1() {
		return usrRnum1;
	}
	public void setUsrRnum1(String usrRnum1) {
		this.usrRnum1 = usrRnum1;
	}
	public String getDepartment() {
		return department;
	}
	public void setDepartment(String department) {
		this.department = department;
	}
	public String getPosition() {
		return position;
	}
	public void setPosition(String position) {
		this.position = position;
	}
	public String getCause() {
		return cause;
	}
	public void setCause(String cause) {
		this.cause = cause;
	}
	public String getHelpYn() {
		return helpYn;
	}
	public void setHelpYn(String helpYn) {
		this.helpYn = helpYn;
	}
}
