/* Generated by Together */

package org.nii.niis.niim.service.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.nii.niis.niim.service.AddressSearchVO;
import org.nii.niis.niim.service.IndexMapVO;
import org.springframework.stereotype.Repository;

import egovframework.rte.psl.dataaccess.EgovAbstractDAO;

/**
 * 행정명 검색 DAO 객체
 */
@Repository("addressSearchDAO")
public class AddressSearchDAO extends EgovAbstractDAO {
	@SuppressWarnings({ "deprecation", "unchecked" })
	public List<AddressSearchVO> getAddressArea(String admcd) throws Exception {
		Map<String, Object> param = new HashMap<String, Object>();
		param.put("admcd", admcd);
		List<AddressSearchVO> list = null;
		if (admcd.length() == 2){
			list = (List<AddressSearchVO>)getSqlMapClientTemplate().queryForList("addressSidoSearchDAO.getAddressArea", param);
		}else if (admcd.length() == 5){
			list = (List<AddressSearchVO>)getSqlMapClientTemplate().queryForList("addressSigunguSearchDAO.getAddressArea", param);
		}else{
			list = (List<AddressSearchVO>)getSqlMapClientTemplate().queryForList("addressDongSearchDAO.getAddressArea", param);
		}
		return list;
	}

	@SuppressWarnings({ "deprecation", "unchecked" })
	public List<IndexMapVO> getIndexMapArea(String selectKey) {
		return (List<IndexMapVO>)getSqlMapClientTemplate().queryForList("addressSearchDAO.getIndexMapArea", selectKey);
	}
	
    
    /**
     * 1:5000도엽을 조회한다.
     * @exception
     */
    public List<IndexMapVO> selectIndexMap5000List(String minx, String miny, String maxx, String maxy) {
		Map<String, Object> param = new HashMap<String, Object>();
		param.put("minx", minx);
		param.put("miny", miny);
		param.put("maxx", maxx);
		param.put("maxy", maxy);
    	return (List<IndexMapVO>)getSqlMapClientTemplate().queryForList("addressSearchDAO.getIndexMap5000", param);
    }
}