/* Generated by Together */

package org.nii.niis.niim.service.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.nii.niis.niim.service.UserVO;
import org.springframework.stereotype.Repository;

import egovframework.rte.psl.dataaccess.EgovAbstractDAO;

/**
 * 사용자 정보 관리 DAO
 * 
 * 로그인, 회원가입, 개인정보 입력 기능을 제공
 */
@Repository("niimLoginDAO")
public class LoginDAO extends EgovAbstractDAO {

	/**
	 * 사용자 로그인
	 * @param id
	 * @param pw
	 * @return List
	 */
	@SuppressWarnings({ "deprecation", "unchecked" })
    public List<UserVO> selectLoginCheck(String id, String pw) {
		Map<String, Object> param = new HashMap<String, Object>();
		param.put("userPW", pw);
		param.put("userID", id);
		return (List<UserVO>) getSqlMapClientTemplate().queryForList("loginDAO.loginCheck", param);
    }
	
	/**
	 * Gpki 사용자 로그인
	 * @param id
	 * @param pw
	 * @return List
	 */
	@SuppressWarnings({ "deprecation", "unchecked" })
    public List<UserVO> selectLoginCheckGpki(String pw) {
		Map<String, Object> param = new HashMap<String, Object>();
		param.put("userPW", pw);
		return (List<UserVO>) getSqlMapClientTemplate().queryForList("loginDAO.loginCheckGpki", param);
    }
	
	/**
	 * 사용자 로그 기록
	 * @param sendMap
	 */
	public void insertLoginLog(Map<String, Object> sendMap) {
		insert("loginDAO.insertLoginLog", sendMap);
	}

    /**
     * 회원가입 
     */
	public boolean insertUserInfo(UserVO userVO) {
    	return false;
    }

    /**
     * 개인정보의 입력 / 수정을 처리하는 메소드 
     */
	public boolean insertPersonData() {
    	return false;
    }

    /**
     * 개인정보 불러오기 
     */
	public UserVO selectPersonData() {
    	return null;
    }
}


