/* Generated by Together */

package org.nii.niis.niim.service.impl;

import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.annotation.Resource;

import org.nii.niis.niim.service.LoginService;
import org.nii.niis.niim.service.UserVO;
import org.springframework.stereotype.Service;

/**
 * 사용자 정보 관리 Service
 * 
 * 로그인, 회원가입, 개인정보 입력 기능을 제공
 */
@Service("niimLoginService")
public class LoginServiceImpl implements LoginService {
	
    @Resource(name="niimLoginDAO")
    private LoginDAO loginDAO;

    /**
	 * 사용자 로그인
	 * @param id
	 * @param pw
	 * @return List
	 * @throws Exception
	 */
    public List<UserVO> getLoginCheck(String id, String pw) throws Exception {
        return loginDAO.selectLoginCheck(id, pw);
    }
    
    /**
	 * 사용자 로그인
	 * @param id
	 * @param pw
	 * @return List
	 * @throws Exception
	 */
    public List<UserVO> getLoginCheckGpki(String pw) throws Exception {
        return loginDAO.selectLoginCheckGpki(pw);
    }
    
    
    /**
	 * 사용자 로그 기록
	 * @param sendMap
	 * @throws Exception
	 */
    @Override
	public void insertLoginLog(String usrMgno, String st, String acsIp, String reqMgno, String systemCde) throws Exception {
    	
    	Map<String, Object> logMap = new HashMap<String, Object>();
    	logMap.put("usrMgno", usrMgno);
    	logMap.put("st", st);
    	logMap.put("acsIp", acsIp);
    	logMap.put("reqMgno", reqMgno);
    	logMap.put("systemCde", systemCde);
    	
    	loginDAO.insertLoginLog(logMap);
	}

    /**
     * 회원가입 
     */
    public boolean setUserInfo(UserVO userVO) {
    	return false;
    }

    /**
     * 개인정보의 입력 / 수정을 처리하는 메소드 
     */
    public boolean setPersonData() {
    	return false;
    }

    /**
     * 개인정보 불러오기 
     */
    public UserVO getPersonData() {
    	return null;
    }

    /**
     * @directed 
     */
    private LoginDAO lnkLoginDAO;
	
}
