/* Generated by Together */

package org.nii.niis.niim.service.impl;

import java.util.List;
import java.util.Map;

import org.springframework.stereotype.Repository;

import egovframework.rte.psl.dataaccess.EgovAbstractDAO;

/**
 * 메인 DAO 객체
 */
@Repository("mainDAO")
public class MainDAO extends EgovAbstractDAO {

	@SuppressWarnings("deprecation")
	public List<?> getCommonCode(Map<String, Object> param) throws Exception {
		return (List<?>) getSqlMapClientTemplate().queryForList("mainDAO.getCommonCode", param);
	}

	@SuppressWarnings("unchecked")
	public Map<String, Object> getMainReqCnt(Map<String, Object> param) throws Exception {
		return (Map<String, Object>)selectByPk("mainDAO.getMainReqCnt", param);
	}
	
}